language: scala
jdk:
  - oraclejdk8
install:
  - mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=libs/organizational-1.0-SNAPSHOT.jar
before_script:
  - mkdir out
  - mkdir out/arduino
  - mkdir out/graphviz
  - mkdir out/python
